export const actionType = {
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    DELETE_ALL_PRODUCT_OF_ONE_TYPE_FROM_CART: 'DELETE_ALL_PRODUCT_OF_ONE_TYPE_FROM_CART',
    EMPTY_BASKET: 'EMPTY_BASKET',
    CHANGE_NUMBER_OF_PRODUCT_BASE_ON_INVENTORY: 'CHANGE_NUMBER_OF_PRODUCT_BASE_ON_INVENTORY'
}