export const ActionTypes = {
    ADMIN_LOGEDIN: 'ADMIN_LOGEDIN',
    ADMIN_LOGEDOUT: 'ADMIN_LOGEDOUT',
    SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
    START_EDITING: 'START_EDINGIT',
    FINISH_EDITING: 'FINISH_EDITING',
    ADD_A_PRODUCT: 'ADD_A_PRODUCT',
    DELETE_A_PRODUCT: 'DELETE_A_PRODUCT',
    SELECT_PRODUCT_TO_DELETE: 'SELECT_PRODUCT_TO_DELETE',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
}